// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tab_it.DAL;

#nullable disable

namespace tab_it.Migrations
{
    [DbContext(typeof(TabItDbContext))]
    [Migration("20260609205051_AddInventoryRecipes")]
    partial class AddInventoryRecipes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("tab_it.Models.Domain.CustomerTab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OpenedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TabCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OpenedByUserId");

                    b.ToTable("CustomerTabs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Notes = "",
                            OpenedAt = new DateTime(2026, 5, 6, 12, 0, 0, 0, DateTimeKind.Utc),
                            OpenedByUserId = 1,
                            Status = 1,
                            TabCode = "TAB-001",
                            TableNumber = 5
                        },
                        new
                        {
                            Id = 2,
                            ClosedAt = new DateTime(2026, 5, 6, 11, 30, 0, 0, DateTimeKind.Utc),
                            Notes = "",
                            OpenedAt = new DateTime(2026, 5, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            OpenedByUserId = 1,
                            Status = 2,
                            TabCode = "TAB-002",
                            TableNumber = 12
                        });
                });

            modelBuilder.Entity("tab_it.Models.Domain.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastRestockedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<decimal>("QuantityOnHand")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ReorderLevel")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("InventoryItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Coffee Beans",
                            QuantityOnHand = 5.000m,
                            ReorderLevel = 1.000m,
                            Sku = "INV-COF-BEAN",
                            Unit = 2
                        },
                        new
                        {
                            Id = 2,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Milk",
                            QuantityOnHand = 12.000m,
                            ReorderLevel = 2.000m,
                            Sku = "INV-MILK",
                            Unit = 3
                        },
                        new
                        {
                            Id = 3,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Cola 0.33L Can",
                            QuantityOnHand = 100.000m,
                            ReorderLevel = 12.000m,
                            Sku = "INV-COLA-033",
                            Unit = 1
                        });
                });

            modelBuilder.Entity("tab_it.Models.Domain.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerTabId")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("OrderedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerTabId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerTabId = 1,
                            DiscountPercent = 0m,
                            OrderNumber = "ORD-001",
                            OrderedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 5,
                            Subtotal = 15.49m,
                            Total = 15.49m
                        },
                        new
                        {
                            Id = 2,
                            CustomerTabId = 2,
                            DiscountPercent = 10m,
                            OrderNumber = "ORD-002",
                            OrderedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 5,
                            Subtotal = 18.50m,
                            Total = 16.65m
                        });
                });

            modelBuilder.Entity("tab_it.Models.Domain.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ItemNote")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ItemNote = "No onions",
                            LineTotal = 12.99m,
                            OrderId = 1,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 12.99m
                        },
                        new
                        {
                            Id = 2,
                            ItemNote = "",
                            LineTotal = 2.50m,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 2.50m
                        },
                        new
                        {
                            Id = 3,
                            ItemNote = "",
                            LineTotal = 15.50m,
                            OrderId = 2,
                            ProductId = 4,
                            Quantity = 1,
                            UnitPrice = 15.50m
                        },
                        new
                        {
                            Id = 4,
                            ItemNote = "",
                            LineTotal = 3.00m,
                            OrderId = 2,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 3.00m
                        });
                });

            modelBuilder.Entity("tab_it.Models.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<bool>("IsAlcoholic")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastRestockedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int>("ProductCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableQuantity = 100,
                            IsAlcoholic = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Cola",
                            ProductCategoryId = 1,
                            Sku = "BEV-001",
                            UnitPrice = 2.50m
                        },
                        new
                        {
                            Id = 2,
                            AvailableQuantity = 50,
                            IsAlcoholic = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Coffee",
                            ProductCategoryId = 1,
                            Sku = "BEV-002",
                            UnitPrice = 3.00m
                        },
                        new
                        {
                            Id = 3,
                            AvailableQuantity = 20,
                            IsAlcoholic = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Cheeseburger",
                            ProductCategoryId = 2,
                            Sku = "MAI-001",
                            UnitPrice = 12.99m
                        },
                        new
                        {
                            Id = 4,
                            AvailableQuantity = 15,
                            IsAlcoholic = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Pepperoni Pizza",
                            ProductCategoryId = 2,
                            Sku = "MAI-002",
                            UnitPrice = 15.50m
                        },
                        new
                        {
                            Id = 5,
                            AvailableQuantity = 10,
                            IsAlcoholic = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Chocolate Cake",
                            ProductCategoryId = 3,
                            Sku = "DES-001",
                            UnitPrice = 6.00m
                        });
                });

            modelBuilder.Entity("tab_it.Models.Domain.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Drinks and refreshments",
                            Name = "Beverages"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Hot meals and main dishes",
                            Name = "Main Course"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sweet treats",
                            Name = "Desserts"
                        });
                });

            modelBuilder.Entity("tab_it.Models.Domain.ProductRecipeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityRequired")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductRecipeItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InventoryItemId = 3,
                            ProductId = 1,
                            QuantityRequired = 1.000m
                        },
                        new
                        {
                            Id = 2,
                            InventoryItemId = 1,
                            ProductId = 2,
                            QuantityRequired = 0.012m
                        });
                });

            modelBuilder.Entity("tab_it.Models.Domain.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Administrator role",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Staff role",
                            Name = "Staff"
                        });
                });

            modelBuilder.Entity("tab_it.Models.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@tab-it.local",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "User",
                            PasswordHash = "admin",
                            RoleId = 1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("tab_it.Models.Domain.CustomerTab", b =>
                {
                    b.HasOne("tab_it.Models.Domain.User", "OpenedByUser")
                        .WithMany("Tabs")
                        .HasForeignKey("OpenedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OpenedByUser");
                });

            modelBuilder.Entity("tab_it.Models.Domain.Order", b =>
                {
                    b.HasOne("tab_it.Models.Domain.CustomerTab", "CustomerTab")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerTabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerTab");
                });

            modelBuilder.Entity("tab_it.Models.Domain.OrderItem", b =>
                {
                    b.HasOne("tab_it.Models.Domain.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tab_it.Models.Domain.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("tab_it.Models.Domain.Product", b =>
                {
                    b.HasOne("tab_it.Models.Domain.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("tab_it.Models.Domain.ProductRecipeItem", b =>
                {
                    b.HasOne("tab_it.Models.Domain.InventoryItem", "InventoryItem")
                        .WithMany("RecipeItems")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tab_it.Models.Domain.Product", "Product")
                        .WithMany("RecipeItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("tab_it.Models.Domain.User", b =>
                {
                    b.HasOne("tab_it.Models.Domain.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("tab_it.Models.Domain.CustomerTab", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("tab_it.Models.Domain.InventoryItem", b =>
                {
                    b.Navigation("RecipeItems");
                });

            modelBuilder.Entity("tab_it.Models.Domain.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("tab_it.Models.Domain.Product", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("RecipeItems");
                });

            modelBuilder.Entity("tab_it.Models.Domain.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("tab_it.Models.Domain.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("tab_it.Models.Domain.User", b =>
                {
                    b.Navigation("Tabs");
                });
#pragma warning restore 612, 618
        }
    }
}
