// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tab_it.DAL;

#nullable disable

namespace tab_it.Migrations
{
    [DbContext(typeof(TabItDbContext))]
    partial class TabItDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("tab_it.Models.Domain.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("OIB")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("tab_it.Models.Domain.CustomerTab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OpenedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TabCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OpenedByUserId");

                    b.ToTable("CustomerTabs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Notes = "",
                            OpenedAt = new DateTime(2026, 5, 6, 12, 0, 0, 0, DateTimeKind.Utc),
                            OpenedByUserId = 1,
                            PaymentMethod = "",
                            Status = 1,
                            TabCode = "TAB-001",
                            TableNumber = 5
                        },
                        new
                        {
                            Id = 2,
                            ClosedAt = new DateTime(2026, 5, 6, 11, 30, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Notes = "",
                            OpenedAt = new DateTime(2026, 5, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            OpenedByUserId = 1,
                            PaymentMethod = "Cash",
                            Status = 2,
                            TabCode = "TAB-002",
                            TableNumber = 12
                        });
                });

            modelBuilder.Entity("tab_it.Models.Domain.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastRestockedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<decimal>("QuantityOnHand")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ReorderLevel")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("InventoryItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Coffee Beans",
                            QuantityOnHand = 5.000m,
                            ReorderLevel = 1.000m,
                            Sku = "INV-COF-BEAN",
                            Unit = 2
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Milk",
                            QuantityOnHand = 12.000m,
                            ReorderLevel = 2.000m,
                            Sku = "INV-MILK",
                            Unit = 3
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Coca Cola 0.33L Can",
                            QuantityOnHand = 100.000m,
                            ReorderLevel = 12.000m,
                            Sku = "INV-COLA-033",
                            Unit = 1
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Fanta 0.33L Can",
                            QuantityOnHand = 80.000m,
                            ReorderLevel = 12.000m,
                            Sku = "INV-FANTA-033",
                            Unit = 1
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sprite 0.33L Can",
                            QuantityOnHand = 80.000m,
                            ReorderLevel = 12.000m,
                            Sku = "INV-SPRITE-033",
                            Unit = 1
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Still Water 0.5L Bottle",
                            QuantityOnHand = 90.000m,
                            ReorderLevel = 18.000m,
                            Sku = "INV-WATER-050",
                            Unit = 1
                        },
                        new
                        {
                            Id = 7,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Orange Juice",
                            QuantityOnHand = 10.000m,
                            ReorderLevel = 2.000m,
                            Sku = "INV-ORANGE-JUICE",
                            Unit = 3
                        },
                        new
                        {
                            Id = 8,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Chocolate Cake Slice",
                            QuantityOnHand = 18.000m,
                            ReorderLevel = 4.000m,
                            Sku = "INV-CAKE-CHOC",
                            Unit = 1
                        },
                        new
                        {
                            Id = 9,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tiramisu Slice",
                            QuantityOnHand = 16.000m,
                            ReorderLevel = 4.000m,
                            Sku = "INV-TIRAMISU",
                            Unit = 1
                        },
                        new
                        {
                            Id = 10,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Cheesecake Slice",
                            QuantityOnHand = 16.000m,
                            ReorderLevel = 4.000m,
                            Sku = "INV-CHEESECAKE",
                            Unit = 1
                        },
                        new
                        {
                            Id = 11,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Apple Pie Slice",
                            QuantityOnHand = 14.000m,
                            ReorderLevel = 4.000m,
                            Sku = "INV-APPLE-PIE",
                            Unit = 1
                        },
                        new
                        {
                            Id = 12,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Croissant",
                            QuantityOnHand = 24.000m,
                            ReorderLevel = 6.000m,
                            Sku = "INV-CROISSANT",
                            Unit = 1
                        },
                        new
                        {
                            Id = 13,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Blueberry Muffin",
                            QuantityOnHand = 20.000m,
                            ReorderLevel = 5.000m,
                            Sku = "INV-MUFFIN-BLUE",
                            Unit = 1
                        },
                        new
                        {
                            Id = 14,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Brownie",
                            QuantityOnHand = 20.000m,
                            ReorderLevel = 5.000m,
                            Sku = "INV-BROWNIE",
                            Unit = 1
                        },
                        new
                        {
                            Id = 15,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Burger Patty",
                            QuantityOnHand = 30.000m,
                            ReorderLevel = 8.000m,
                            Sku = "INV-BURGER-PATTY",
                            Unit = 1
                        },
                        new
                        {
                            Id = 16,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Burger Bun",
                            QuantityOnHand = 30.000m,
                            ReorderLevel = 8.000m,
                            Sku = "INV-BURGER-BUN",
                            Unit = 1
                        },
                        new
                        {
                            Id = 17,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Pizza Dough",
                            QuantityOnHand = 25.000m,
                            ReorderLevel = 6.000m,
                            Sku = "INV-PIZZA-DOUGH",
                            Unit = 1
                        },
                        new
                        {
                            Id = 18,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Pepperoni",
                            QuantityOnHand = 3.000m,
                            ReorderLevel = 0.500m,
                            Sku = "INV-PEPPERONI",
                            Unit = 2
                        },
                        new
                        {
                            Id = 19,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Cheese",
                            QuantityOnHand = 5.000m,
                            ReorderLevel = 1.000m,
                            Sku = "INV-CHEESE",
                            Unit = 2
                        },
                        new
                        {
                            Id = 20,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sandwich Bread",
                            QuantityOnHand = 60.000m,
                            ReorderLevel = 12.000m,
                            Sku = "INV-SAND-BREAD",
                            Unit = 1
                        },
                        new
                        {
                            Id = 21,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Chicken",
                            QuantityOnHand = 6.000m,
                            ReorderLevel = 1.000m,
                            Sku = "INV-CHICKEN",
                            Unit = 2
                        },
                        new
                        {
                            Id = 22,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Lettuce",
                            QuantityOnHand = 3.000m,
                            ReorderLevel = 0.700m,
                            Sku = "INV-LETTUCE",
                            Unit = 2
                        },
                        new
                        {
                            Id = 23,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Caesar Dressing",
                            QuantityOnHand = 4.000m,
                            ReorderLevel = 0.750m,
                            Sku = "INV-CAESAR-DRESS",
                            Unit = 3
                        });
                });

            modelBuilder.Entity("tab_it.Models.Domain.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerTabId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("OrderedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerTabId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerTabId = 1,
                            DiscountPercent = 0m,
                            IsDeleted = false,
                            OrderNumber = "ORD-001",
                            OrderedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 5,
                            Subtotal = 15.49m,
                            Total = 15.49m
                        },
                        new
                        {
                            Id = 2,
                            CustomerTabId = 2,
                            DiscountPercent = 10m,
                            IsDeleted = false,
                            OrderNumber = "ORD-002",
                            OrderedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 5,
                            Subtotal = 18.50m,
                            Total = 16.65m
                        });
                });

            modelBuilder.Entity("tab_it.Models.Domain.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ItemNote")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            ItemNote = "No onions",
                            LineTotal = 12.99m,
                            OrderId = 1,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 12.99m
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            ItemNote = "",
                            LineTotal = 2.50m,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 2.50m
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            ItemNote = "",
                            LineTotal = 15.50m,
                            OrderId = 2,
                            ProductId = 4,
                            Quantity = 1,
                            UnitPrice = 15.50m
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            ItemNote = "",
                            LineTotal = 3.00m,
                            OrderId = 2,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 3.00m
                        });
                });

            modelBuilder.Entity("tab_it.Models.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsAlcoholic")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastRestockedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int>("ProductCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableQuantity = 100,
                            IsAlcoholic = false,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Coca Cola 0.33L",
                            ProductCategoryId = 1,
                            Sku = "BEV-001",
                            UnitPrice = 2.50m
                        },
                        new
                        {
                            Id = 2,
                            AvailableQuantity = 50,
                            IsAlcoholic = false,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Coffee with Milk",
                            ProductCategoryId = 1,
                            Sku = "BEV-002",
                            UnitPrice = 3.00m
                        },
                        new
                        {
                            Id = 3,
                            AvailableQuantity = 20,
                            IsAlcoholic = false,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Cheeseburger",
                            ProductCategoryId = 2,
                            Sku = "MAI-001",
                            UnitPrice = 12.99m
                        },
                        new
                        {
                            Id = 4,
                            AvailableQuantity = 15,
                            IsAlcoholic = false,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Pepperoni Pizza",
                            ProductCategoryId = 2,
                            Sku = "MAI-002",
                            UnitPrice = 15.50m
                        },
                        new
                        {
                            Id = 5,
                            AvailableQuantity = 10,
                            IsAlcoholic = false,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Chocolate Cake",
                            ProductCategoryId = 3,
                            Sku = "DES-001",
                            UnitPrice = 6.00m
                        },
                        new
                        {
                            Id = 6,
                            AvailableQuantity = 0,
                            IsAlcoholic = false,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Espresso",
                            ProductCategoryId = 1,
                            Sku = "BEV-003",
                            UnitPrice = 2.20m
                        },
                        new
                        {
                            Id = 7,
                            AvailableQuantity = 0,
                            IsAlcoholic = false,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Cappuccino",
                            ProductCategoryId = 1,
                            Sku = "BEV-004",
                            UnitPrice = 3.40m
                        },
                        new
                        {
                            Id = 8,
                            AvailableQuantity = 0,
                            IsAlcoholic = false,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Latte",
                            ProductCategoryId = 1,
                            Sku = "BEV-005",
                            UnitPrice = 3.60m
                        },
                        new
                        {
                            Id = 9,
                            AvailableQuantity = 0,
                            IsAlcoholic = false,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Fanta 0.33L",
                            ProductCategoryId = 1,
                            Sku = "BEV-006",
                            UnitPrice = 2.50m
                        },
                        new
                        {
                            Id = 10,
                            AvailableQuantity = 0,
                            IsAlcoholic = false,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sprite 0.33L",
                            ProductCategoryId = 1,
                            Sku = "BEV-007",
                            UnitPrice = 2.50m
                        },
                        new
                        {
                            Id = 11,
                            AvailableQuantity = 0,
                            IsAlcoholic = false,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Still Water 0.5L",
                            ProductCategoryId = 1,
                            Sku = "BEV-008",
                            UnitPrice = 1.80m
                        },
                        new
                        {
                            Id = 12,
                            AvailableQuantity = 0,
                            IsAlcoholic = false,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Orange Juice",
                            ProductCategoryId = 1,
                            Sku = "BEV-009",
                            UnitPrice = 3.20m
                        },
                        new
                        {
                            Id = 13,
                            AvailableQuantity = 0,
                            IsAlcoholic = false,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tiramisu",
                            ProductCategoryId = 3,
                            Sku = "DES-002",
                            UnitPrice = 5.50m
                        },
                        new
                        {
                            Id = 14,
                            AvailableQuantity = 0,
                            IsAlcoholic = false,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Cheesecake",
                            ProductCategoryId = 3,
                            Sku = "DES-003",
                            UnitPrice = 5.80m
                        },
                        new
                        {
                            Id = 15,
                            AvailableQuantity = 0,
                            IsAlcoholic = false,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Apple Pie",
                            ProductCategoryId = 3,
                            Sku = "DES-004",
                            UnitPrice = 4.80m
                        },
                        new
                        {
                            Id = 16,
                            AvailableQuantity = 0,
                            IsAlcoholic = false,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Croissant",
                            ProductCategoryId = 3,
                            Sku = "DES-005",
                            UnitPrice = 2.70m
                        },
                        new
                        {
                            Id = 17,
                            AvailableQuantity = 0,
                            IsAlcoholic = false,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Blueberry Muffin",
                            ProductCategoryId = 3,
                            Sku = "DES-006",
                            UnitPrice = 3.10m
                        },
                        new
                        {
                            Id = 18,
                            AvailableQuantity = 0,
                            IsAlcoholic = false,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Club Sandwich",
                            ProductCategoryId = 2,
                            Sku = "MAI-003",
                            UnitPrice = 8.90m
                        },
                        new
                        {
                            Id = 19,
                            AvailableQuantity = 0,
                            IsAlcoholic = false,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Caesar Salad",
                            ProductCategoryId = 2,
                            Sku = "MAI-004",
                            UnitPrice = 7.80m
                        },
                        new
                        {
                            Id = 20,
                            AvailableQuantity = 0,
                            IsAlcoholic = false,
                            IsDeleted = false,
                            LastRestockedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Brownie",
                            ProductCategoryId = 3,
                            Sku = "DES-007",
                            UnitPrice = 3.90m
                        });
                });

            modelBuilder.Entity("tab_it.Models.Domain.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Drinks and refreshments",
                            IsDeleted = false,
                            Name = "Beverages"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Hot meals and main dishes",
                            IsDeleted = false,
                            Name = "Main Course"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sweet treats",
                            IsDeleted = false,
                            Name = "Desserts"
                        });
                });

            modelBuilder.Entity("tab_it.Models.Domain.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages", (string)null);
                });

            modelBuilder.Entity("tab_it.Models.Domain.ProductRecipeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityRequired")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductRecipeItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InventoryItemId = 3,
                            IsDeleted = false,
                            ProductId = 1,
                            QuantityRequired = 1.000m
                        },
                        new
                        {
                            Id = 2,
                            InventoryItemId = 1,
                            IsDeleted = false,
                            ProductId = 2,
                            QuantityRequired = 0.012m
                        },
                        new
                        {
                            Id = 3,
                            InventoryItemId = 2,
                            IsDeleted = false,
                            ProductId = 2,
                            QuantityRequired = 0.100m
                        },
                        new
                        {
                            Id = 4,
                            InventoryItemId = 15,
                            IsDeleted = false,
                            ProductId = 3,
                            QuantityRequired = 1.000m
                        },
                        new
                        {
                            Id = 5,
                            InventoryItemId = 16,
                            IsDeleted = false,
                            ProductId = 3,
                            QuantityRequired = 1.000m
                        },
                        new
                        {
                            Id = 6,
                            InventoryItemId = 17,
                            IsDeleted = false,
                            ProductId = 4,
                            QuantityRequired = 1.000m
                        },
                        new
                        {
                            Id = 7,
                            InventoryItemId = 18,
                            IsDeleted = false,
                            ProductId = 4,
                            QuantityRequired = 0.050m
                        },
                        new
                        {
                            Id = 8,
                            InventoryItemId = 19,
                            IsDeleted = false,
                            ProductId = 4,
                            QuantityRequired = 0.120m
                        },
                        new
                        {
                            Id = 9,
                            InventoryItemId = 8,
                            IsDeleted = false,
                            ProductId = 5,
                            QuantityRequired = 1.000m
                        },
                        new
                        {
                            Id = 10,
                            InventoryItemId = 1,
                            IsDeleted = false,
                            ProductId = 6,
                            QuantityRequired = 0.009m
                        },
                        new
                        {
                            Id = 11,
                            InventoryItemId = 1,
                            IsDeleted = false,
                            ProductId = 7,
                            QuantityRequired = 0.012m
                        },
                        new
                        {
                            Id = 12,
                            InventoryItemId = 2,
                            IsDeleted = false,
                            ProductId = 7,
                            QuantityRequired = 0.100m
                        },
                        new
                        {
                            Id = 13,
                            InventoryItemId = 1,
                            IsDeleted = false,
                            ProductId = 8,
                            QuantityRequired = 0.012m
                        },
                        new
                        {
                            Id = 14,
                            InventoryItemId = 2,
                            IsDeleted = false,
                            ProductId = 8,
                            QuantityRequired = 0.180m
                        },
                        new
                        {
                            Id = 15,
                            InventoryItemId = 4,
                            IsDeleted = false,
                            ProductId = 9,
                            QuantityRequired = 1.000m
                        },
                        new
                        {
                            Id = 16,
                            InventoryItemId = 5,
                            IsDeleted = false,
                            ProductId = 10,
                            QuantityRequired = 1.000m
                        },
                        new
                        {
                            Id = 17,
                            InventoryItemId = 6,
                            IsDeleted = false,
                            ProductId = 11,
                            QuantityRequired = 1.000m
                        },
                        new
                        {
                            Id = 18,
                            InventoryItemId = 7,
                            IsDeleted = false,
                            ProductId = 12,
                            QuantityRequired = 0.250m
                        },
                        new
                        {
                            Id = 19,
                            InventoryItemId = 9,
                            IsDeleted = false,
                            ProductId = 13,
                            QuantityRequired = 1.000m
                        },
                        new
                        {
                            Id = 20,
                            InventoryItemId = 10,
                            IsDeleted = false,
                            ProductId = 14,
                            QuantityRequired = 1.000m
                        },
                        new
                        {
                            Id = 21,
                            InventoryItemId = 11,
                            IsDeleted = false,
                            ProductId = 15,
                            QuantityRequired = 1.000m
                        },
                        new
                        {
                            Id = 22,
                            InventoryItemId = 12,
                            IsDeleted = false,
                            ProductId = 16,
                            QuantityRequired = 1.000m
                        },
                        new
                        {
                            Id = 23,
                            InventoryItemId = 13,
                            IsDeleted = false,
                            ProductId = 17,
                            QuantityRequired = 1.000m
                        },
                        new
                        {
                            Id = 24,
                            InventoryItemId = 20,
                            IsDeleted = false,
                            ProductId = 18,
                            QuantityRequired = 2.000m
                        },
                        new
                        {
                            Id = 25,
                            InventoryItemId = 21,
                            IsDeleted = false,
                            ProductId = 18,
                            QuantityRequired = 0.120m
                        },
                        new
                        {
                            Id = 26,
                            InventoryItemId = 22,
                            IsDeleted = false,
                            ProductId = 18,
                            QuantityRequired = 0.030m
                        },
                        new
                        {
                            Id = 27,
                            InventoryItemId = 21,
                            IsDeleted = false,
                            ProductId = 19,
                            QuantityRequired = 0.120m
                        },
                        new
                        {
                            Id = 28,
                            InventoryItemId = 22,
                            IsDeleted = false,
                            ProductId = 19,
                            QuantityRequired = 0.120m
                        },
                        new
                        {
                            Id = 29,
                            InventoryItemId = 23,
                            IsDeleted = false,
                            ProductId = 19,
                            QuantityRequired = 0.030m
                        },
                        new
                        {
                            Id = 30,
                            InventoryItemId = 14,
                            IsDeleted = false,
                            ProductId = 20,
                            QuantityRequired = 1.000m
                        });
                });

            modelBuilder.Entity("tab_it.Models.Domain.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Administrator role",
                            IsDeleted = false,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Staff role",
                            IsDeleted = false,
                            Name = "Staff"
                        });
                });

            modelBuilder.Entity("tab_it.Models.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@tab-it.local",
                            FirstName = "Admin",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "User",
                            PasswordHash = "admin",
                            RoleId = 1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("tab_it.Models.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("tab_it.Models.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tab_it.Models.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("tab_it.Models.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("tab_it.Models.Domain.CustomerTab", b =>
                {
                    b.HasOne("tab_it.Models.Domain.User", "OpenedByUser")
                        .WithMany("Tabs")
                        .HasForeignKey("OpenedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OpenedByUser");
                });

            modelBuilder.Entity("tab_it.Models.Domain.Order", b =>
                {
                    b.HasOne("tab_it.Models.Domain.CustomerTab", "CustomerTab")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerTabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerTab");
                });

            modelBuilder.Entity("tab_it.Models.Domain.OrderItem", b =>
                {
                    b.HasOne("tab_it.Models.Domain.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tab_it.Models.Domain.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("tab_it.Models.Domain.Product", b =>
                {
                    b.HasOne("tab_it.Models.Domain.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("tab_it.Models.Domain.ProductImage", b =>
                {
                    b.HasOne("tab_it.Models.Domain.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("tab_it.Models.Domain.ProductRecipeItem", b =>
                {
                    b.HasOne("tab_it.Models.Domain.InventoryItem", "InventoryItem")
                        .WithMany("RecipeItems")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tab_it.Models.Domain.Product", "Product")
                        .WithMany("RecipeItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("tab_it.Models.Domain.User", b =>
                {
                    b.HasOne("tab_it.Models.Domain.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("tab_it.Models.Domain.CustomerTab", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("tab_it.Models.Domain.InventoryItem", b =>
                {
                    b.Navigation("RecipeItems");
                });

            modelBuilder.Entity("tab_it.Models.Domain.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("tab_it.Models.Domain.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("OrderItems");

                    b.Navigation("RecipeItems");
                });

            modelBuilder.Entity("tab_it.Models.Domain.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("tab_it.Models.Domain.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("tab_it.Models.Domain.User", b =>
                {
                    b.Navigation("Tabs");
                });
#pragma warning restore 612, 618
        }
    }
}
